[book]
authors = ["Dion Dokter"]
language = "en"
src = "src"
title = "device-driver-book"

[output.html]
git-repository-url = "https://github.com/diondokter/device-driver"
git-repository-icon = "fas-code"
